- hosts: 10.3.1.100
  become : yes
  tasks:
  - name: Install JDK
    apt: name=default-jdk state=latest

  - name: Add Jenkins Key
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present

  - name: Add Jenkins Repository 
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable/binary/jenkins_2.7.1_all.deb'

  - name: Install Jenkins
    apt: name=jenkins

