- hosts: homologacao, producao
  #become : yes
  tasks:
  - name: Install JDK
    apt: 
      name: default-jdk 
      state: latest
  
  - name: Install Tomcat 7
    apt:
      name: tomcat7

  - name: Start Tomcat
    service:
      name: tomcat7 
      state: started
    




