- hosts: jenkins
  become : yes
  tasks:
  - name: Install JDK
    apt: name=default-jdk state=latest

  - name: Install Jenkins
    apt: 
     deb: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.7.1_all.deb
     state: present

