# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :jenkins do |jenkins_config|
    jenkins_config.vm.hostname = "jenkins"
    jenkins_config.vm.network :private_network,
                              :ip => "10.3.1.100"

    jenkins_config.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "playbooks/playbook-install-jenkins.yml"
    end
  end

  config.vm.define :web01 do |web01_config|
    web01_config.vm.hostname = "web01"
    web01_config.vm.network :private_network,
                            :ip => "10.3.1.101"
  end

  config.vm.define :web02 do |web02_config|
    web02_config.vm.hostname = "web02"
    web02_config.vm.network :private_network,
    		            :ip => "10.3.1.102"
  end
end
