# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :jenkins do |jenkins_config|
    jenkins_config.vm.hostname = "jenkins"
    jenkins_config.vm.network :private_network,
                              :ip => "10.3.1.100"

    jenkins_config.vm.provision :ansible do |ansible|
      ansible.playbook = "playbooks/playbook-install-jenkins.yml"
    end
  end

  config.vm.define :homologacao do |homologacao_config|
    homologacao_config.vm.hostname = "homologacao"
    homologacao_config.vm.network :private_network,
                            :ip => "10.3.1.101"

    homologacao_config.vm.provision :ansible do |ansible|
      ansible.playbook = "playbooks/playbook-install-web.yml"
    end
  end

  config.vm.define :producao do |producao_config|
    producao_config.vm.hostname = "producao"
    producao_config.vm.network :private_network,
    		            :ip => "10.3.1.102"
  end
end
